# Generated by Django 4.2.1 on 2023-05-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='Bdate',
            field=models.CharField(max_length=100),
        ),
    ]
